Improvements to the classic auxiliary binding policy implementation
The aim is to improve error messages by using parameter names from the operator signature + using add_note on existing errors instead of generating wrapping errors.

Example:
```
In [1]: from koladata import kd
In [2]: arolla.M.math.add(object(), object())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

TypeError: unsupported type: object
Error occurred while processing argument: `x`
```

Previously, the error was
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<traceback>

TypeError: unsupported type: object

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<traceback>

TypeError: unable to represent as QValue or Expr: args[0]: object
```
PiperOrigin-RevId: 748313821
Change-Id: I2155c6b55702f5e719895d9ae8f83cd69bb5ee64