Remove unnecessary error clarifications from arolla_bridge
- Adding `op_name` was often misleading, as Arolla operator name is different from Koda one. For example, `array.count` instead of `slices.agg_count`.
- The additional messages we passed to `OperatorEvalError` seem useless: too specific for external users and too obvious for developers familiar with the code. The only one I kept is `"cannot align inputs to a common shape"`.
- I pass `.VerboseRuntimeErrors(false)` to hide internal Arolla stack traces.

Before:
```
KodaError: math.floordiv: successfully converted input DataSlice(s) to DenseArray(s) but failed to evaluate the Arolla operator

The cause is: division by zero; during evaluation of operator math.floordiv
NODE: M.math.floordiv(L.a0, L.a1)
```

After:
```
KodaError: division by zero
```
PiperOrigin-RevId: 712505986
Change-Id: I7eb0c5c3aa98f9a11ef2202b70b38f1411c7478a