Reduce error nesting in argument processing for the full binding policy
The idea is to use: `ex.add_note(...)` instead of `raise NewError(...) from ex`.

Example:
```
In [1]: from koladata import kd
In [2]: kd.add([1], 2)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<traceback>

ValueError: passing a Python list to a Koda operation is ambiguous. Please use kd.slice(...) to create a slice or a multi-dimensional slice, and kd.list(...) to create a single Koda list
Error occurred while processing argument: `x`
```
PiperOrigin-RevId: 748299185
Change-Id: Ie406503559f197906ad9e68c0770a52f844e207f