Simplify EagerOperator.__call__
This change slightly reduces the python overhead for eager operators and hides the __call__ method within the traceback when an operator fails.

```
from koladata import kd

_1 = kd.item(1)
%timeit kd.math.add(_1, _1)  # 1.64us -> 1.23us

print(kd.math.add(_1))
# Traceback (most recent call last):
#   File "test.py", line 3, in <module>
#     kd.math.add(_1)
#     ~~~~~~~~~~~^^^
# TypeError: missing 1 required positional argument: 'y'
```

PiperOrigin-RevId: 865722954
Change-Id: I7a5374c3f531dcb346e7c9882cd8ac641ff974ab